#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''trilegal - Waqas Bhatti (wbhatti@astro.princeton.edu) - Dec 2017
License: MIT. See the LICENSE file for more details.

This downloads and interacts with galaxy models generated by the TRILEGAL
webform.

Requires the requests package and can be used without astrobase if necessary.

'''
import os
import os.path
import pickle
import gzip
import glob

import logging
from datetime import datetime
from traceback import format_exc

import numpy as np
import numpy.random as npr
# seed the numpy random generator
npr.seed(0xdecaff)

import scipy.stats as sps
import scipy.interpolate as spi

import matplotlib
matplotlib.use('Agg')

import matplotlib.pyplot as plt

import requests

#############
## LOGGING ##
#############

# setup a logger
LOGGER = None

def set_logger_parent(parent_name):
    globals()['LOGGER'] = logging.getLogger('%s.trilegal' % parent_name)

def LOGDEBUG(message):
    if LOGGER:
        LOGGER.debug(message)
    elif DEBUG:
        print('%sZ [DBUG]: %s' % (datetime.utcnow().isoformat(), message))

def LOGINFO(message):
    if LOGGER:
        LOGGER.info(message)
    else:
        print('%sZ [INFO]: %s' % (datetime.utcnow().isoformat(), message))

def LOGERROR(message):
    if LOGGER:
        LOGGER.error(message)
    else:
        print('%sZ [ERR!]: %s' % (datetime.utcnow().isoformat(), message))

def LOGWARNING(message):
    if LOGGER:
        LOGGER.warning(message)
    else:
        print('%sZ [WRN!]: %s' % (datetime.utcnow().isoformat(), message))

def LOGEXCEPTION(message):
    if LOGGER:
        LOGGER.exception(message)
    else:
        print(
            '%sZ [EXC!]: %s\nexception was: %s' % (
                datetime.utcnow().isoformat(),
                message, format_exc()
            )
        )


################################
## QUERYING THE TRILEGAL FORM ##
################################

POSTURL = 'http://stev.oapd.inaf.it/cgi-bin/trilegal_{formversion}'

POST_INPUT_PARAMS = [
    'binary_kind',
    'extinction_infty',
    'extinction_sigma',
    'gc_b',
    'gc_l',
    'field',
    'icm_lim',
    'mag_lim',
    'photsys_file',
    'trilegal_version'
]

# these are taken from get_trilegal.pm, a Perl script from Prof. Leo Girardi
# a version of this is at T. D. Morton's VESPA github repository:
# https://github.com/timothydmorton/VESPA/blob/master/scripts/get_trilegal
POST_DEFAULT_PARAMS = {
    'binary_frac': '0.3',
    'binary_kind': '${use_binaries}',
    'binary_mrinf': '0.7',
    'binary_mrsup': '1',
    'bulge_a': '1',
    'bulge_a0': '95',
    'bulge_am': '2500',
    'bulge_b': '-2.0e9',
    'bulge_csi': '0.31',
    'bulge_cutoffmass': '0.01',
    'bulge_eta': '0.68',
    'bulge_file': 'tab_sfr/file_sfr_bulge_zoccali_p03.dat',
    'bulge_kind': '2',
    'bulge_phi0': '15',
    'bulge_rho_central': '406.0',
    'eq_alpha': '0',
    'eq_delta': '0',
    'extinction_h_r': '100000',
    'extinction_h_z': '110',
    'extinction_infty': '${avextinction}',
    'extinction_kind': '2',
    'extinction_rho_sun': '0.00015',
    'extinction_sigma': '${sigmaav_av}',
    'field': '${area}',
    'gal_coord': '1',
    'gc_b': '${gal_b}',
    'gc_l': '${gal_l}',
    'halo_a': '1',
    'halo_b': '0',
    'halo_file': 'tab_sfr/file_sfr_halo.dat',
    'halo_kind': '2',
    'halo_q': '0.65',
    'halo_r_eff': '2800',
    'halo_rho_sun': '0.00015',
    'icm_lim': '${icmlim}',
    'imf_file': 'tab_imf/imf_chabrier_lognormal.dat',
    'mag_lim': '${maglim}',
    'mag_res': '0.1',
    'object_a': '1',
    'object_av': '1.504',
    'object_avkind': '1',
    'object_b': '0',
    'object_cutoffmass': '0.8',
    'object_dist': '1658',
    'object_file': 'tab_sfr/file_sfr_m4.dat',
    'object_kind': '0',
    'object_mass': '1280',
    'output_kind': '1',
    'photsys_file': 'tab_mag_odfnew/tab_mag_${system}.dat',
    'r_sun': '8700',
    'submit_form': 'Submit',
    'thickdisk_a': '1',
    'thickdisk_b': '0',
    'thickdisk_file': 'tab_sfr/file_sfr_thickdisk.dat',
    'thickdisk_h_r': '2800',
    'thickdisk_h_z': '800',
    'thickdisk_kind': '0',
    'thickdisk_r_max': '15000',
    'thickdisk_r_min': '0',
    'thickdisk_rho_sun': '0.0015',
    'thindisk_a': '0.8',
    'thindisk_b': '0',
    'thindisk_file': 'tab_sfr/file_sfr_thindisk_mod.dat',
    'thindisk_h_r': '2800',
    'thindisk_h_z0': '95',
    'thindisk_hz_alpha': '1.6666',
    'thindisk_hz_tau0': '4400000000',
    'thindisk_kind': '3',
    'thindisk_r_max': '15000',
    'thindisk_r_min': '0',
    'thindisk_rho_sun': '59',
    'trilegal_version': '${version}',
    'z_sun': '24.2'
}


# these were extracted from the TRILEGAL HTML form at:
# http://stev.oapd.inaf.it/cgi-bin/trilegal
FILTER_SYSTEMS = {
    'tab_mag_odfnew/tab_mag_2mass.dat': '2MASS JHKs',
    'tab_mag_odfnew/tab_mag_2mass_spitzer_wise.dat': '2MASS + Spitzer (IRAC+MIPS) + WISE',
    'tab_mag_odfnew/tab_mag_2mass_spitzer_wise_washington_ddo51.dat': '2MASS+Spitzer+WISE+Washington+DDO51',
    'tab_mag_odfnew/tab_mag_TESS_2mass_kepler.dat': 'TESS + 2MASS (Vegamags) + Kepler + SDSS griz + DDO51 (in ABmags)',
    'tab_mag_odfnew/tab_mag_UVbright.dat': 'HST+GALEX+Swift/UVOT UV filters',
    'tab_mag_odfnew/tab_mag_acs_hrc.dat': 'HST/ACS HRC',
    'tab_mag_odfnew/tab_mag_acs_wfc.dat': 'HST/ACS WFC',
    'tab_mag_odfnew/tab_mag_akari.dat': 'AKARI',
    'tab_mag_odfnew/tab_mag_batc.dat': 'BATC',
    'tab_mag_odfnew/tab_mag_bessell.dat': 'UBVRIJHKLMN (cf. Bessell 1990 + Bessell & Brett 1988)',
    'tab_mag_odfnew/tab_mag_ciber.dat': 'CIBER',
    'tab_mag_odfnew/tab_mag_dcmc.dat': 'DCMC',
    'tab_mag_odfnew/tab_mag_decam.dat': 'DECAM (ABmags)',
    'tab_mag_odfnew/tab_mag_decam_vista.dat': 'DECAM ugrizY (ABmags) + VISTA ZYJHKs (Vegamags)',
    'tab_mag_odfnew/tab_mag_denis.dat': 'DENIS',
    'tab_mag_odfnew/tab_mag_dmc14.dat': 'DMC 14 filters',
    'tab_mag_odfnew/tab_mag_dmc15.dat': 'DMC 15 filters',
    'tab_mag_odfnew/tab_mag_eis.dat': 'ESO/EIS (WFI UBVRIZ + SOFI JHK)',
    'tab_mag_odfnew/tab_mag_gaia.dat': "Gaia's G, G_BP and G_RP (Vegamags)",
    'tab_mag_odfnew/tab_mag_galex.dat': "GALEX FUV+NUV (Vegamag) + Johnson's UBV",
    'tab_mag_odfnew/tab_mag_galex_sloan.dat': 'GALEX FUV+NUV + SDSS ugriz (all ABmags)',
    'tab_mag_odfnew/tab_mag_int_wfc.dat': 'INT/WFC (Vegamag)',
    'tab_mag_odfnew/tab_mag_iphas.dat': 'IPHAS',
    'tab_mag_odfnew/tab_mag_jwst_wide.dat': 'planned JWST wide        filters',
    'tab_mag_odfnew/tab_mag_kepler.dat': 'Kepler + SDSS griz + DDO51 (in ABmags)',
    'tab_mag_odfnew/tab_mag_kepler_2mass.dat': 'Kepler + SDSS griz + DDO51 (in ABmags) + 2MASS (~Vegamag)',
    'tab_mag_odfnew/tab_mag_lbt_lbc.dat': 'LBT/LBC (Vegamag)',
    'tab_mag_odfnew/tab_mag_lsst.dat': 'LSST ugrizY, March 2012 total filter throughputs (all ABmags)',
    'tab_mag_odfnew/tab_mag_megacam.dat': "CFHT/Megacam u*g'r'i'z'",
    'tab_mag_odfnew/tab_mag_megacam_wircam.dat': 'CFHT Megacam + Wircam (all ABmags)',
    'tab_mag_odfnew/tab_mag_nicmosab.dat': 'HST/NICMOS AB',
    'tab_mag_odfnew/tab_mag_nicmosst.dat': 'HST/NICMOS ST',
    'tab_mag_odfnew/tab_mag_nicmosvega.dat': 'HST/NICMOS vega',
    'tab_mag_odfnew/tab_mag_noao_ctio_mosaic2.dat': 'NOAO/CTIO/MOSAIC2 (Vegamag)',
    'tab_mag_odfnew/tab_mag_ogle.dat': 'OGLE-II',
    'tab_mag_odfnew/tab_mag_ogle_2mass_spitzer.dat': 'OGLE + 2MASS + Spitzer (IRAC+MIPS)',
    'tab_mag_odfnew/tab_mag_panstarrs1.dat': 'Pan-STARRS1',
    'tab_mag_odfnew/tab_mag_sloan.dat': 'SDSS ugriz',
    'tab_mag_odfnew/tab_mag_sloan_2mass.dat': 'SDSS ugriz + 2MASS JHKs',
    'tab_mag_odfnew/tab_mag_sloan_ukidss.dat': 'SDSS ugriz + UKIDSS ZYJHK',
    'tab_mag_odfnew/tab_mag_spitzer.dat': 'Spitzer IRAC+MIPS',
    'tab_mag_odfnew/tab_mag_spitzer.dat': 'Spitzer IRAC+MIPS',
    'tab_mag_odfnew/tab_mag_stis.dat': 'HST/STIS imaging mode',
    'tab_mag_odfnew/tab_mag_stroemgren.dat': 'Stroemgren-Crawford',
    'tab_mag_odfnew/tab_mag_suprimecam.dat': 'Subaru/Suprime-Cam (ABmags)',
    'tab_mag_odfnew/tab_mag_swift_uvot.dat': 'SWIFT/UVOT UVW2, UVM2, UVW1,u (Vegamag)',
    'tab_mag_odfnew/tab_mag_tycho2.dat': 'Tycho VTBT',
    'tab_mag_odfnew/tab_mag_ubvrijhk.dat': 'UBVRIJHK (cf. Maiz-Apellaniz 2006 + Bessell 1990)',
    'tab_mag_odfnew/tab_mag_ukidss.dat': 'UKIDSS ZYJHK (Vegamag)',
    'tab_mag_odfnew/tab_mag_vilnius.dat': 'Vilnius',
    'tab_mag_odfnew/tab_mag_visir.dat': 'VISIR',
    'tab_mag_odfnew/tab_mag_vista.dat': 'VISTA ZYJHKs (Vegamag)',
    'tab_mag_odfnew/tab_mag_vphas.dat': 'VPHAS+ (ABmags)',
    'tab_mag_odfnew/tab_mag_vst_omegacam.dat': 'VST/OMEGACAM (ABmag)',
    'tab_mag_odfnew/tab_mag_washington.dat': 'Washington CMT1T2',
    'tab_mag_odfnew/tab_mag_washington_ddo51.dat': 'Washington CMT1T2 + DDO51',
    'tab_mag_odfnew/tab_mag_wfc3_medium.dat': 'HST/WFC3 medium filters (UVIS1+IR, final throughputs)',
    'tab_mag_odfnew/tab_mag_wfc3_verywide.dat': 'HST/WFC3 long-pass and extremely wide filters (UVIS1, final throughputs)',
    'tab_mag_odfnew/tab_mag_wfc3_wide.dat': 'HST/WFC3 wide filters (UVIS1+IR, final throughputs)',
    'tab_mag_odfnew/tab_mag_wfc3_wideverywide.dat': 'HST/WFC3 all W+LP+X filters (UVIS1+IR, final throughputs)',
    'tab_mag_odfnew/tab_mag_wfc3ir.dat': 'HST/WFC3 IR channel (final throughputs)',
    'tab_mag_odfnew/tab_mag_wfc3uvis1.dat': 'HST/WFC3 UVIS channel, chip 1 (final throughputs)',
    'tab_mag_odfnew/tab_mag_wfc3uvis2.dat': 'HST/WFC3 UVIS channel, chip 2 (final throughputs)',
    'tab_mag_odfnew/tab_mag_wfi.dat': 'ESO/WFI',
    'tab_mag_odfnew/tab_mag_wfi2.dat': 'ESO/WFI2',
    'tab_mag_odfnew/tab_mag_wfi_sofi.dat': 'ESO/WFI+SOFI',
    'tab_mag_odfnew/tab_mag_wfpc2.dat': 'HST/WFPC2 (Vegamag, cf. Holtzman et al. 1995)',
    'tab_mag_odfnew/tab_mag_wircam.dat': 'CFHT Wircam'
}
